version: '3'

services:
  
  backend_nogaspi:
    depends_on:
      - db_nogaspi
      - phpmyadmin_nogaspi
    build:
      context: ${path}/Nogaspi/nogaspi
      args:
        - WD=Nogaspi
    container_name: backend_nogaspi
    restart: always
    environment:
      workdir: Nogaspi
      PMA_HOST: db_nogaspi
      MYSQL_ROOT_PASSWORD: ${sqlPassword}
      FIREBASE_SERVICE_ACCOUNT: ${fireBaseServiceAccount}
    ports:
      - 5556:5000
    volumes:
      - ${path}:/usr/src/app
    networks:
      - python-db

  db_nogaspi:
    image: mariadb:latest
    container_name: db_nogaspi
    restart: always
    ports:
      - "33307:3306"
    volumes:
      - data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${sqlPassword}
      MYSQL_DATABASE: nogaspi
      MYSQL_USER: ${sqlUser}
      MYSQL_PASSWORD: ${sqlPassword}
    networks:
      - python-db
      - phpmyadmin-db

  phpmyadmin_nogaspi:
    depends_on:
      - db_nogaspi
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_nogaspi
    restart: always
    environment:
      PMA_HOST: db_nogaspi
      MYSQL_ROOT_PASSWORD: ${sqlPassword}
    ports:
      - "8082:80"
    networks:
      - phpmyadmin-db
  
  pytest_nogaspi:
    depends_on:
      - db_nogaspi_test
    build:
      context: ${path}/${testDirectory}/test
      args:
        - WD=${testDirectory}
    container_name: backend_nogaspi_test
    environment:
      PMA_HOST: db_nogaspi_test
      MYSQL_ROOT_PASSWORD: ${sqlPassword}
      FIREBASE_SERVICE_ACCOUNT: ${fireBaseServiceAccount}
    ports:
      - 6556:5000
    volumes:
      - ${path}:/usr/src/app
    networks:
      - python-db_test

  db_nogaspi_test:
    image: mariadb:latest
    container_name: db_nogaspi_test
    ports:
      - "34307:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${sqlPassword}
      MYSQL_DATABASE: nogaspi
      MYSQL_USER: ${sqlUser}
      MYSQL_PASSWORD: ${sqlPassword}
    networks:
      - python-db_test

  build_nogaspi:
    build:
      context: ${path}/${buildDirectory}/nogaspi
      args:
        - WD=${buildDirectory}
    container_name: build_nogaspi
    volumes:
      - ${path}:/usr/src/app

volumes:
  data:

networks:
  python-db:
    driver: bridge
  phpmyadmin-db:
    driver: bridge
  python-db_test:
    driver: bridge
