EXPIRATION_DATE_TOLERANCE_IN_DAY = 15
TOKEN_VALIDITY = 1440  # minutes
CONFIRMATION_CODE_VALIDITY = 10  # minutes
DONATION_CODE_VALIDITY = 5  #minutes
DISTANCE_MAX_TO_SEND_NOTIFICATION_IN_NEW_DONATION = 500  # meters
ANDROID_MAIN_ACTIVITY = "com.example.modulescan.activity.MainActivity"
MAX_LETTER_COUNT_ON_NOTIFICATION = 100
PRODUCT_DATA_VALIDITY = 60  # days