EXPIRATION_DATE_TOLERANCE_IN_DAY = 15
TOKEN_VALIDITY = 1440  # minutes
CONFIRMATION_CODE_VALIDITY = 10  # minutes
DONATION_CODE_VALIDITY = 5  #minutes
DISTANCE_MAX_TO_SEND_NOTIFICATION_IN_NEW_DONATION = 1000000  # meter