from .generateRegularPath import generateRegularPath as user_generateRegularPath
from .getRegularPath import getRegularPath as user_getRegularPath
from .postFireBaseToken import postFireBaseToken as user_postFireBaseToken
from .getMyInfos import getMyInfos as user_getMyInfos